gitian.yml: try fix linux build
try fix the gitian compile error by installing libboost-dev:
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter  -DBOOST_SPIRIT_THREADSAFE -I/home/ubuntu/build/blackcoin/src -I/home/ubuntu/build/blackcoin/src/obj -I/home/ubuntu/install/include -DUSE_UPNP=1 -DENABLE_WALLET -I/home/ubuntu/build/blackcoin/src/leveldb/include -I/home/ubuntu/build/blackcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/wallet.d -o obj/wallet.o wallet.cpp
wallet.cpp:18:37: warning: boost/range/algorithm.hpp: No such file or directory
wallet.cpp: In member function ‘bool CWallet::SelectCoinsMinConfByCoinAge(int64_t, unsigned int, int, int, std::vector<COutput, std::allocator<COutput> >, std::set<std::pair<const CWalletTx*, unsigned int>, std::less<std::pair<const CWalletTx*, unsigned int> >, std::allocator<std::pair<const CWalletTx*, unsigned int> > >&, int64_t&) const’:
wallet.cpp:1265: error: ‘sort’ is not a member of ‘boost’